### ISSUE TITLE
Sandbox #2 | Where in the World?

### ISSUE THREAD

**Issue by dt-woods** [spatial-data-discovery/ay1920-2#2]
# The Challenge
A client has asked you to identify where in the world a set of photos were taken. If possible, they would really like to see these locations as points on a map. All you have access to are the [original JPEG image files (zip)](https://drive.google.com/uc?export=download&id=1dvjJCJUVb-Z1fi262Rmm0pStryXp8Sik).

Your challenge is to write a script that reads the coordinates from each image file, save the coordinates to a GeoJSON plain text file noting which image each set of coordinates belongs to, and, display the coordinates on a map to easily identify from where the photos were taken.

Save your script to the **sandbox** folder of our **ay1920-2** repository with the file name "yourname_sb2.py" (e.g., `davis_sb2.py`).

Drag-and-drop an image of your point-location map into the Issue comments on GitHub. Please respect the repository and scale your images such that they are 1000 kB or less.

Keep track of the methods you use and the resources you find along the way.

# Background

## The Vector Data Model
The vector data model for geographic information systems includes geometries for points, lines, and polygons (aka areas). For photographs, it is of interest to map point locations associated with where the photos were taken. To map point locations on the globe, there are three key pieces of information needed:

1. angular unit of measurement
1. origin
1. datum

The angular unit of measure for our global coordinate reference system (CGS) is defined by the lines of [longitude](https://en.wikipedia.org/wiki/Longitude) and [latitude](https://en.wikipedia.org/wiki/Latitude) measured in degrees from the origin. For most geographic coordinate systems (GCS), the origin is assumed to be where the [equator](https://en.wikipedia.org/wiki/Equator) touches the [prime meridian](https://en.wikipedia.org/wiki/Prime_meridian). A model for Earth's surface (or datum) is also provided for a given GCS. The most commonly used GCS for the whole world is the 1984 World Geodetic System ([WGS84](https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84)), which is also referred to by the International Association of Oil & Gas Producers registry code, EPSG:4326. Given these three pieces of information, we can identify any given point on the globe.

## The GeoJSON File Format
With dimension zero, the most fundamental geometry in the vector data model is the point. To store point data, all you need are its coordinates (the x and the y or the longitude and latitude). Moreover, with spatial data, a given point may have meaning or context that is inherently important to that location (e.g., a name, an address, an elevation, a time-stamped image). These attributes should live with the coordinate in the dataset

One data format for storing such information is the geographic javascript object notation or GeoJSON. This format allows for the storage of all vector data model geometries (points, lines and polygons) as features or feature collections, providing a link to attributes, such as names or titles. This file format is written in plain text format with a file extension .json or .geojson.

There are several Python libraries available for reading/writing to JSON file types or you may simply write to file and follow the [current GeoJSON convention](https://geojson.org/).

## The JPEG Image File Format
The modern JPEG (.jpg or .jpeg) file format allows for more than just compressed image data. Notably, the format allows for several types of metadata to be stored within the image file. The application-specific metadata known as Exif (exchangeable image file format) tags store several key pieces of information, including what is commonly referred to as location services metadata (aka spatial data). These metadata are stored thanks to the proliferation of inexpensive GPS receivers in modern smartphones.

There are libraries in the Python programming language that can read and extract GPS data from decoded Exif tags.

## References

[More than you ever wanted to know about GeoJSON](https://macwright.org/2015/03/23/geojson-second-bite.html) by Tom MacWright (2015).

**Comment by intj1** [comment]
![coors](https://user-images.githubusercontent.com/11450372/73996070-907f4200-4928-11ea-876d-22241ba4f471.PNG)

**Comment by Matt-KC** [comment]
![mkcusick_sb2_map](https://user-images.githubusercontent.com/14205515/74077467-ebc73800-49ed-11ea-91b8-1425619b6e4b.png)

**Comment by Elkelthen** [comment]
![image](https://user-images.githubusercontent.com/47184997/74090012-e6f99700-4a74-11ea-83da-39e5c8f3700a.png)

**Comment by abgaddi** [comment]
<img width="615" alt="Screen Shot 2020-02-11 at 2 12 08 PM" src="https://user-images.githubusercontent.com/56974751/74270523-5c65a180-4cd9-11ea-8052-8d4e54d5c95f.png">

**Comment by grluisi** [comment]
![Screen Shot 2020-02-11 at 2 46 48 PM](https://user-images.githubusercontent.com/60242278/74273888-2d522e80-4cdf-11ea-8391-cf19136e0277.png)
