### ISSUE TITLE
Sandbox #5 | Visualizing

### ISSUE THREAD

**Issue by dt-woods** [spatial-data-discovery/ay1920-2#5]
Using any of the ASCII raster files in our `data` directory, try creating a visualization using a software of your choice (e.g., QGIS). You may apply any symbology (colors, gradients, transparencies) and include any additional spatial dataset that you see fit.

Please drag-and-drop your image to the comments of this issue (please be mindful of image sizes, scaling to about 1200 px width or less or link to a large file to download). 

What were the biggest challenges you found working on your visualization?

**Comment by Elkelthen** [comment]
![image](https://user-images.githubusercontent.com/47184997/75397636-5c62c580-58c5-11ea-871a-2c7df1accac9.png)

Had a slight issue where I needed to invert my numbers, but it was all pretty straightforward.

**Comment by Matt-KC** [comment]
![image](https://user-images.githubusercontent.com/14205515/75460209-2cf89b00-594f-11ea-8b41-c1c6c3ce3a8a.png)

I didn't experience any issues using QGIS. Found out I could copy a link for the image straight from QGIS and paste it here.

**Comment by leanlow** [comment]
![image](https://user-images.githubusercontent.com/55556360/75486765-22ec9180-597b-11ea-99a4-b784a023958f.png)
It was easy to set a palette that was already by QGIS, however it was difficult to change each individual color as they were connected to the other colors. Changing one hue would alter the rest and change the image.

**Comment by aburke01** [comment]
![aburke01](https://user-images.githubusercontent.com/55194019/75487920-56c8b680-597d-11ea-941d-46be10f73d14.png)

**Comment by grluisi** [comment]
![Screen Shot 2020-02-27 at 4 50 32 PM](https://user-images.githubusercontent.com/60242278/75492838-9b0c8480-5986-11ea-9c18-76ed4b83b20a.png)

**Comment by gnmaniaci** [comment]
<img width="500" alt="maniaciSandbox5" src="https://user-images.githubusercontent.com/46606018/75784068-a4537380-5d2f-11ea-81a0-51c04f36a040.png">


It wasn't too hard to figure out qgis, but I definitely had to google search how to change colors and things like that. I think with more practice, I could really get the hang of it. I had some fun adjusting everything and  making this beautiful letter G.
