### ISSUE TITLE
Sparse Data Challenge

### ISSUE THREAD

**Issue by dt-woods** [spatial-data-discovery/ay1920-2#6]
# The Challenge
You have been given three ASC raster files that represent the red, green, and blue color bands of a satellite image; however, you will note that about 80% of the pixels in each band are missing (i.e., assigned NODATA_VALUE).

Your task, should you choose to accept it, is to create a gapless version of the image.

You may assume that the following hold true:

1. Each ASC raster file has the same CELLSIZE and spatiotemporal extent (i.e., they all represent the same area at the same time).
1. Pixel values represent red, green and blue color bands, which should only have values between 0-254; no values should be outside this range.
1. The XLLCENTER and YLLCENTER are not correct in the ASC headers.

### Instructions
Create a complete raster dataset based on the input files (red.txt, green.txt, blue.txt) where all NODATA_VALUE pixels have been assigned an integer.

1. Work with your partner(s) to brainstorm an approach and develop your solution
1. Please comment to this issue with your and your partner's names
1. If you were not in class on Tuesday, 3 March 2020, then you may work on this problem individually
1. You may use any methods to produce a single gapless image
1. Push your one solution to the `ay1920-2/sdc` directory before next class that includes the following:
    - a Python script with your solution methods (`initials_intials.py`) or as much of a solution as you have
    - if possible, convert your output to a PNG/JPG image (`initials_initials.png`); __please do not upload ASC raster solutions to the repository; they are too big and we can just run your code on the input files to see your output__
1. Answer the discussion board questions before next class

### Grading
**5 pt**

| Component | Full Marks |
|:----------|-----------:|
| Python script reads ASC raster data into a usable format | 1 |
| A method was developed toward gapfilling missing pixel values | 1 |
| Python script runs without errors | 0.5 |
| Discussion | 2.5 |

**Comment by jlollen** [comment]
Team Members: Jenna Ollen and Lu Huynh

**Comment by intj1** [comment]
Team Member: LeAnn Lo, Tinh Son

**Comment by gnmaniaci** [comment]
Team Members: Gianna Maniaci, Jonah Casale

**Comment by grluisi** [comment]
Team Members: Grant Luisi, Matthew Cusick

**Comment by PulakRaj** [comment]
Team Members: Pulak Raj, Nikhil Daga

**Comment by Elkelthen** [comment]
John and Emma, btw

**Comment by dt-woods** [comment]
https://www.nasa.gov/topics/earth/earthday/lena_delta.html
